services:
  - type: web
    name: my-flask-app
    repo: https://github.com/pepexqw/app # замените на ваш репозиторий
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    env: python
